services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  pdf-processor:
    build: .venv\
    volumes:
      - ${PDF_DIR}:/app/pdfs
      - ${RUTA_SALIDA}:/app/pdfsoutput
    environment:
      - PDF_DIR=/app/pdfs
      - RUTA_SALIDA=/app/pdfsoutput
      - PYTHONUNBUFFERED=1
      - ES_HOST=elasticsearch
      - ES_PORT=9200
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic

  
volumes:
  elasticsearch-data:
    driver: local

networks:
  elastic:
    driver: bridge