services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    env_file:
      - ../envs/elasticsearch.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
      
    networks:
      elastic_network:
        ipv4_address: 192.168.5.3

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  pdf-processor:
    build:
      context: ../
      dockerfile: compose/backend/Dockerfile

    env_file:
      - ../envs/pdf-processor.env
    volumes:
      - ${PDF_DIR}:/app/pdfs
      - ${RUTA_SALIDA}:/app/pdfsoutput
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      elastic_network:
        ipv4_address: 192.168.5.4

  web-app:
    build: 
      context: ../
      dockerfile: compose/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - pdf-processor
    networks:
      elastic_network:
        ipv4_address: 192.168.5.5
  
volumes:
  elasticsearch-data:
    driver: local

networks:
  elastic_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.5.0/24
          gateway: 192.168.5.1